Repository DMSport/DMSport-iOS, pull requests merged in 2022-10, with the labels that each got.

#2 ⚙️ :: (#1) tuist project setting
  .package.resolved
  DMSport/Project.swift
  DMSport/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  DMSport/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  DMSport/Resources/Assets.xcassets/Contents.json
  DMSport/Resources/LaunchScreen.storyboard
  DMSport/Sources/App/AppDelegate.swift
  DMSport/Sources/App/SceneDelegate.swift
  DMSport/Sources/Base/BaseVC.swift
  DMSport/Sources/Scene/Login/LoginTemp.swift
  DMSport/Support/Info.plist
  DMSport/Support/TempInfo.swift
  Service/Project.swift
  Service/Sources/Service.swift
  ThirdPartyLib/Project.swift
  ThirdPartyLib/Sources/TempSource.swift
  Tuist/Config.swift
  Tuist/ProjectDescriptionHelpers/DynamicFramework.swift
  Tuist/ProjectDescriptionHelpers/MakeModule.swift
  Tuist/ProjectDescriptionHelpers/OrganizationName.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
  Workspace.swift
Labels: setting

#4 🐛 :: fix generate bug
  Makefile
Labels: setting

#5 🐛 :: fix makefile bug
  Makefile
Labels: setting

#11 ✨ :: (#10) base 파일 생성
  DMSport/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  DMSport/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.png
  DMSport/Resources/Assets.xcassets/AppIcon.appiconset/Icon-120 1.png
  DMSport/Resources/Assets.xcassets/AppIcon.appiconset/Icon-120.png
  DMSport/Resources/Assets.xcassets/AppIcon.appiconset/Icon-152.png
  DMSport/Resources/Assets.xcassets/AppIcon.appiconset/Icon-167.png
  DMSport/Resources/Assets.xcassets/AppIcon.appiconset/Icon-180.png
  DMSport/Resources/Assets.xcassets/AppIcon.appiconset/Icon-20.png
  DMSport/Resources/Assets.xcassets/AppIcon.appiconset/Icon-29.png
  DMSport/Resources/Assets.xcassets/AppIcon.appiconset/Icon-40 1.png
  DMSport/Resources/Assets.xcassets/AppIcon.appiconset/Icon-40 2.png
  DMSport/Resources/Assets.xcassets/AppIcon.appiconset/Icon-40.png
  DMSport/Resources/Assets.xcassets/AppIcon.appiconset/Icon-58 1.png
  DMSport/Resources/Assets.xcassets/AppIcon.appiconset/Icon-58.png
  DMSport/Resources/Assets.xcassets/AppIcon.appiconset/Icon-60.png
  DMSport/Resources/Assets.xcassets/AppIcon.appiconset/Icon-76.png
  DMSport/Resources/Assets.xcassets/AppIcon.appiconset/Icon-80 1.png
  DMSport/Resources/Assets.xcassets/AppIcon.appiconset/Icon-80.png
  DMSport/Resources/Assets.xcassets/AppIcon.appiconset/Icon-87.png
  DMSport/Resources/Assets.xcassets/Megaphone_bright.imageset/Contents.json
  DMSport/Resources/Assets.xcassets/Megaphone_bright.imageset/Megaphone_bright.svg
  DMSport/Resources/Assets.xcassets/Megaphone_dark.imageset/Contents.json
  DMSport/Resources/Assets.xcassets/Megaphone_dark.imageset/Megaphone_dark.svg
  DMSport/Resources/Assets.xcassets/Person_bright.imageset/Contents.json
  DMSport/Resources/Assets.xcassets/Person_bright.imageset/Person_bright.svg
  DMSport/Resources/Assets.xcassets/Person_dark.imageset/Contents.json
  DMSport/Resources/Assets.xcassets/Person_dark.imageset/Person_dark.svg
  DMSport/Resources/Assets.xcassets/Vote_bright.imageset/Contents.json
  DMSport/Resources/Assets.xcassets/Vote_bright.imageset/Vote_bright.svg
  DMSport/Resources/Assets.xcassets/Vote_dark.imageset/Contents.json
  DMSport/Resources/Assets.xcassets/Vote_dark.imageset/Vote_dark.svg
  DMSport/Resources/Color.xcassets/BackgroundColor.colorset/Contents.json
  DMSport/Resources/Color.xcassets/BaseColor.colorset/Contents.json
  DMSport/Resources/Color.xcassets/BlackColor.colorset/Contents.json
  DMSport/Resources/Color.xcassets/Contents.json
  DMSport/Resources/Color.xcassets/DisabledColor.colorset/Contents.json
  DMSport/Resources/Color.xcassets/ErrorColor.colorset/Contents.json
  DMSport/Resources/Color.xcassets/HighlightColor.colorset/Contents.json
  DMSport/Resources/Color.xcassets/HintColor.colorset/Contents.json
  DMSport/Resources/Color.xcassets/MainColor.colorset/Contents.json
  DMSport/Resources/Color.xcassets/SelectedColor.colorset/Contents.json
  DMSport/Resources/Color.xcassets/SubtitleColor.colorset/Contents.json
  DMSport/Resources/Color.xcassets/WhiteColor.colorset/Contents.json
  DMSport/Resources/DMSport_Logo.png
  DMSport/Resources/LaunchScreen.storyboard
  DMSport/Sources/App/SceneDelegate.swift
  DMSport/Sources/Base/BaseNC.swift
  DMSport/Sources/Base/BaseTC.swift
  DMSport/Sources/Base/BaseVC.swift
  DMSport/Sources/Base/TabBarVC.swift
Labels: 기능 추가

#12 ✨ :: (#06) create login setup
  DMSport/Resources/Assets.xcassets/CloseEye.imageset/Contents.json
  DMSport/Resources/Assets.xcassets/CloseEye.imageset/i.png
  DMSport/Resources/Assets.xcassets/DMSLoginButton.imageset/Contents.json
  DMSport/Resources/Assets.xcassets/DMSLoginButton.imageset/DMSLogin.png
  DMSport/Resources/Assets.xcassets/DMSSignButton.imageset/Contents.json
  DMSport/Resources/Assets.xcassets/DMSSignButton.imageset/DMSSignButton.png
  DMSport/Resources/Assets.xcassets/OpenEye.imageset/Contents.json
  DMSport/Resources/Assets.xcassets/OpenEye.imageset/OpenEye.png
  DMSport/Resources/Assets.xcassets/Primary.colorset/Contents.json
  DMSport/Resources/Assets.xcassets/Primary2.colorset/Contents.json
  DMSport/Resources/Assets.xcassets/choek.imageset/Contents.json
  DMSport/Resources/Assets.xcassets/choek.imageset/choek.png
  DMSport/Resources/Assets.xcassets/errorImage.imageset/Contents.json
  DMSport/Resources/Assets.xcassets/errorImage.imageset/errorImage.png
  DMSport/Resources/Assets.xcassets/nButton.imageset/Contents.json
  DMSport/Resources/Assets.xcassets/nButton.imageset/nButton.png
  DMSport/Resources/Assets.xcassets/okButton.imageset/Contents.json
  DMSport/Resources/Assets.xcassets/okButton.imageset/okButton.png
  DMSport/Sources/App/SceneDelegate.swift
  DMSport/Sources/Base/BaseVC.swift
  DMSport/Sources/Model/RequestModel.swift
  DMSport/Sources/Scene/Login/Reactor/LoginReactor.swift
  DMSport/Sources/Scene/Login/SignupVC.swift
  DMSport/Sources/Scene/Login/UI/BaseSignView.swift
  DMSport/Sources/Scene/Login/UI/SignViewConfigure.swift
  DMSport/Sources/Scene/Login/UI/SignViewModel.swift
  DMSport/Sources/Scene/Login/UI/Signin/LoginConfigure.swift
  DMSport/Sources/Scene/Login/UI/Signin/LoginModel.swift
  DMSport/Sources/Scene/Login/UI/Signin/LoginVC.swift
  DMSport/Sources/Scene/Login/UI/Signin/LoginView.swift
  DMSport/Sources/Scene/Login/UI/Signin/LoginViewModel.swift
  DMSport/Sources/Scene/Login/UI/Signin/MainPageVC.swift
  DMSport/Sources/Scene/Login/UI/Signup/SignupConfigure.swift
  DMSport/Sources/Scene/Login/UI/Signup/SignupView.swift
  DMSport/Sources/Scene/Login/UI/gmailCertification/GmailCertificationVC.swift
Labels: 기능 추가

#14 ♻️ :: (#13) code refactoring
  .idea/workspace.xml
  DMSport/Sources/Scene/Login/Reactor/LoginReactor.swift
  DMSport/Sources/Scene/Login/SignupVC.swift
  DMSport/Sources/Scene/Login/UI/BaseSignView.swift
  DMSport/Sources/Scene/Login/UI/SignViewConfigure.swift
  DMSport/Sources/Scene/Login/UI/SignViewModel.swift
  DMSport/Sources/Scene/Login/UI/Signin/LoginConfigure.swift
  DMSport/Sources/Scene/Login/UI/Signin/LoginModel.swift
  DMSport/Sources/Scene/Login/UI/Signin/LoginVC.swift
  DMSport/Sources/Scene/Login/UI/Signin/LoginView.swift
  DMSport/Sources/Scene/Login/UI/Signin/LoginViewModel.swift
  DMSport/Sources/Scene/Login/UI/Signin/MainPageVC.swift
  DMSport/Sources/Scene/Login/UI/Signin/아년.swift
  DMSport/Sources/Scene/Login/UI/Signup/SignupConfigure.swift
  DMSport/Sources/Scene/Login/UI/Signup/SignupView.swift
  DMSport/Sources/Scene/Login/UI/gmailCertification/GmailCertificationVC.swift
Labels: 리팩토링

#16 ♻️ :: (#15) code refactoring
  DMSport/Sources/Scene/Login/LoginTemp.swift
  DMSport/Sources/Scene/Login/UI/SignViewModel.swift
  DMSport/Sources/Scene/Login/UI/Signin/LoginConfigure.swift
  DMSport/Sources/Scene/Login/UI/Signin/LoginVC.swift
  DMSport/Sources/Scene/Login/UI/Signup/SignupConfigure.swift
Labels: 리팩토링
